export const localAPIRoutes = {
    CREATE: '/api/strapi/create/?path=',
    CREATE_MANY: '/api/strapi/create-many/?path=',
    DELETE_MANY: '/api/strapi/delete-many/?path=',
    GET: '/api/strapi/get/?path=',
}

export const strapiAPIRoutes = {
    BUTTON: '/buttons',
    // HOME: "/main",
    // HOME_V2: "/home-v2",
    // TRANSFER_MONEY: "/transfer-money",
    JOB_POSTINGS: "/job-postings",
    // CAREER: "/career",
    // BLOG: {
    //     INDEX: "/blog-and-press-room",
    //     LIST: "/blogs",
    // },
    // BLOGS_MAP: '/blogs?fields[0]=slug&fields[1]=date&fields[2]=category&fields[3]=updatedAt&pagination[limit]=300',
    // BLOGS: "/bp-blog",
    // PRESS_ROOM: "/bp-pressroom",
    // ABOUT_US: "/about-us",
    // PARTNER_WITH_US: "/partner-with-us",
    // PRIVACY_POLICY: "/privacy-policy",
    // SAFE_HARBOR_POLICY: "/safe-harbor-policy",
    // TERMS_OF_USE: "/terms-of-use",
    // REGULATORY_INFORMATION: {
    //     INDEX: "/regulatory-information",
    //     TABS: "/regulatory-information-tab-contents",
    // },
    // E_SIGN_CONSENT_AGREEMENT: "/e-sign-consent-agreement",
    // COOKIE_POLICY: "/cookie-policy",
    FX_DAILY: "/fx-dailies",
    FX_WEEKLY: "/fx-weeklies",
    // FX_MONTHLY: "/cu-fx-monthly",
    // FX_FORECAST: "/cu-fx-forecast",
    BANNER: "/banners",
    // CURRENCY_UPDATE: "/currency-update",
    CURRENCY_LIST: "/currency-lists",
    COUNTRY_LIST: "/country-lists",
    GLOBAL_PAYMENT_TAB_CONTENT: "/tab-contents",
    RISK_MANAGEMENT_TABS: "/risk-management-tabs",
    // BUSINESS: {
    //     SMALL_BUSINESS: "/small-business",
    //     MEDIUM_BUSINESS: "/medium-business",
    //     MULTINATIONAL: "/multinational",
    //     ONLINE_SELLER: "/online-seller",
    //     GLOBAL: {
    //         INTERNATIONAL: "/international-payment",
    //         INCOMING: "/incoming-payment",
    //         BATCH: "/batch-payment",
    //         MULTI: "/multi-currency-account",
    //     },
    //     RISK: {
    //         FORWARD: "/forward-contract",
    //         MARKET: "/market-order",
    //     },
    //     LAYOUT: "/layout",
    // },
    INSDUSTRY_SOLUTIONS: "/industry-solution-posts",
    TOOLS: "/tools",
    // SITE_MAP: "/site-map",
    // FAQ: {
    //     INDEX: "/faq-page",
    //     LIST: "/faqs",
    // },
    // TESTIMONIAL: {
    //     INDEX: "/customer-testimonial",
    //     LIST: "/testimonials",
    // },
    // COMPARE_CHART: "/compare-chart",
    // SITE_CONFIG: "/site-config",
    CURRENCY_DROPDOWN: "/currency-dropdowns",
    // CURRENCY_CONVERSION: "/currency-conversion",
    // FX_PAYMENT: "/fx-payment",
    TABS: "/tab-items",
    // MAIN_FOOTER: "/main-footer",
    // MAIN_FOOTER_V2: "/main-footer-v2",
    LANDING_PAGES: "/landing-pages",
    // ECONOMIC_EVENTS: "/economic-events",
    // ECONOMIC_EVENTS_WITH_DATE: "/economic-events-with-dates",
    MTFX_FEES: "/mtfx-fees",
    CURRENCY_BUFFER: "/currency-buffers",
    // FX_MONTHLY_V2: "/fx-monthly-v2",
    // FX_DAILY_UPDATE: "/fx-daily-update",
    // FX_DAILY_V3: "/fx-daily-v3",
    // DAILY_TRADING_TABLE: "/daily-trading-table",
    // DAILY_ECONOMIC_TABLE: "/daily-economic-table",
    // DAILY_MARKET_UPDATE_TABLE: "/daily-market-update-table",
    // FX_MONTHLY_US: "/fx-monthly-us",
    // TOP_BANNER: "/top-banner",
    // NAV_MENU_ITEMS: "/nav-menu-items",
    // LANDING_PAGE_HEADER: "/landing-page-headers",
    // LANDING_PAGE_WIDGET_CONTENT: "/landing-page-widgets",
    // POST_LAYOUT: "/post-layout",
};
