export const localAPIRoutes = {
    CREATE: '/api/strapi/create/?path=',
    CREATE_MANY: '/api/strapi/create-many/?path=',
    DELETE_MANY: '/api/strapi/delete-many/?path=',
    DELETE_ALL_MEDIA: '/api/strapi/delete-all-media/?path=',
    GET: '/api/strapi/get/?path=',
    UPDATE: '/api/strapi/update/?path=',
    UPLOAD: '/api/strapi/upload/?path=',
}

export const mediaAPIRoutes = {
    GET: "/upload/files",
    POST: "/upload",
}

export const strapiAPIRoutesForCollections = {
    BANNERS: "/banners",
    BLOGS: "/blogs",
    BOARDS: "/boards",
    BUTTONS: '/buttons',
    COUNTRY_LIST: "/country-lists",
    CURRENCY_BUFFERS: "/currency-buffers",
    CURRENCY_CHARTS: "/currency-charts",
    CURRENCY_DROPDOWN: "/currency-dropdowns",
    CURRENCY_LIST: "/currency-lists",
    CHECKLISTS: "/checklists",
    FAQs: "/faqs",
    FX_DAILY: "/fx-dailies",
    FX_WEEKLY: "/fx-weeklies",
    GLOBAL_PAYMENT_TAB_CONTENT: "/tab-contents",
    INSDUSTRY_SOLUTIONS: "/industry-solution-posts",
    JOB_POSTINGS: "/job-postings",
    LANDING_PAGES: "/landing-pages",
    MTFX_FEES: "/mtfx-fees",
    RISK_MANAGEMENT_TABS: "/risk-management-tabs",
    TABS: "/regulatory-information-tab-contents",
    TABS: "/tab-items",
    TESTIMONIALS: "/testimonials",
    TOOLS: "/tools",
};

export const strapiAPIRoutesForSingleTypes = {
    ABOUT_US: "/about-us",
    BATCH_PAYMENTS: "/batch-payment",
    // BLOGS_MAP: '/blogs?fields[0]=slug&fields[1]=date&fields[2]=category&fields[3]=updatedAt&pagination[limit]=300',
    // BUSINESS_LAYOUT: "/layout",
    CAREER: "/career",
    COMPARE_CHART: "/compare-chart",
    COOKIE_POLICY: "/cookie-policy",
    CURRENCY_CONVERSION: "/currency-conversion",
    CURRENCY_UPDATE: "/currency-update",
    // DAILY_ECONOMIC_TABLE: "/daily-economic-table",
    // DAILY_MARKET_UPDATE_TABLE: "/daily-market-update-table",
    // DAILY_TRADING_TABLE: "/daily-trading-table",
    E_SIGN_CONSENT_AGREEMENT: "/e-sign-consent-agreement",
    // ECONOMIC_EVENTS_WITH_DATE: "/economic-events-with-dates",
    // ECONOMIC_EVENTS: "/economic-events",
    FORWARD_CONTRACT: "/forward-contract",
    // FX_DAILY_UPDATE: "/fx-daily-update",
    // FX_DAILY_V3: "/fx-daily-v3",
    FX_FORECAST: "/cu-fx-forecast",
    // FX_MONTHLY_US: "/fx-monthly-us",
    // FX_MONTHLY_V2: "/fx-monthly-v2",
    FX_MONTHLY: "/cu-fx-monthly",
    FX_PAYMENT: "/fx-payment",
    // HOME_V2: "/home-v2",
    HOME: "/main",
    INCOMING: "/incoming-payment",
    INTERNATIONAL: "/international-payment",
    // LANDING_PAGE_HEADER: "/landing-page-headers",
    // LANDING_PAGE_WIDGET_CONTENT: "/landing-page-widgets",
    MAIN_FOOTER_V2: "/main-footer-v2",
    // MAIN_FOOTER: "/main-footer",
    MARKET_ORDER: "/market-order",
    MEDIUM_BUSINESS: "/medium-business",
    MULTI_CURRENCY_ACCOUNT: "/multi-currency-account",
    MULTINATIONAL: "/multinational",
    // NAV_MENU_ITEMS: "/nav-menu-items",
    ONLINE_SELLER: "/online-seller",
    PARTNER_WITH_US: "/partner-with-us",
    // POST_LAYOUT: "/post-layout",
    PRESS_ROOM: "/bp-pressroom",
    PRIVACY_POLICY: "/privacy-policy",
    // REGULATORY_INFORMATION: "/regulatory-information",
    SAFE_HARBOR_POLICY: "/safe-harbor-policy",
    SITE_CONFIG: "/site-config",
    SITE_MAP: "/site-map",
    SMALL_BUSINESS: "/small-business",
    TERMS_OF_USE: "/terms-of-use",
    // TOP_BANNER: "/top-banner",
    TRANSFER_MONEY: "/transfer-money",
}
